remote_theme: "mmistakes/so-simple-theme"

locale: fr-FR
title: "Saucispace"
description: "L'espace du saucisson."
baseurl: "/"
url: "https://saucisson.github.io"
logo:
date_format: "%d %B %Y"

read_time: true
words_per_minute: 200

mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics:
disqus:
  shortname: "albanlinard"
twitter:
  username: "AlbanLinard"

liquid:
  error_mode: strict

permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

paginate: 20
paginate_path: /page:num/

search_full_content: false

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

author: albanlinard

footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
